const express = require('express')
const server = express()
server.listen(3000, () => console.log("Run"))
const route = require('./route')
const path = require('path')
const { dirname } = require('path')

server.set('view engine', 'ejs')
server.use(express.static("public"))
server.set('views', path.join(__dirname, 'views'))
server.use(route)